name: Send Logs to Teams

on:
  workflow_run:
    workflows: ["hello World"]  # Triggered by another workflow
    types:
      - completed

jobs:
  send-logs-to-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Workflow Logs
        run: |
          chmod +x scripts/downloadslog.sh
          bash scripts/downloadslog.sh

      - name: Send Logs to Teams
        run: |
          chmod +x scripts/sendtoteams.sh
          bash scripts/sendtoteams.sh
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}


