# name: Send Logs to Teams

# on:
#   workflow_run:
#     workflows: ["hello World"]  # Triggered by another workflow
#     types:
#       - completed

# jobs:
#   send-logs-to-teams:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Download Workflow Logs
#         run: |
#           chmod +x scripts/downloadslog.sh
#           ./scripts/downloadslog.sh

#       - name: Send Logs to Teams
#         run: |
#           chmod +x scripts/sendtoteams.sh
#           ./scripts/sendtoteams.sh
#         env:
#           WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
#           GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}


name: Send Workflow Logs to Teams

on:
  workflow_run:
    workflows: ["hello World"]  # Replace with the name of your primary workflow
    types:
      - completed

jobs:
  send-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Workflow Logs to Teams
        run: |
          chmod +x ./scripts/sendtoteams.sh
          ./scripts/sendtoteams.sh
        env:
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.MY_TOKEN }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}